config/routes.rb
YouTube::Application.routes.draw do

  devise_for :users

  root :to => 'users#index', as: :index

  get '/profile' => 'users#profile', as: :profile

  get '/search' => 'videos#search', as: :search

  get '/search/videos' => 'videos#videos'

  post '/lifts/videos' => 'videos#create', as: :create

  ########LIFTS##########

  get '/lifts' => 'lifts#index', as: :lifts_index

  post '/lifts' => 'lifts#create', as: :videos

  get '/lifts/videos' => 'lifts#lifts_videos', as: :lifts_videos

  get '/lifts/:id' => 'lifts#show', as: :lifts_show

  #to delete a single video
  delete '/lifts/videos/:id' => 'lifts#destroy'

  #Will not allow users to delete entire categories
  # delete '/lifts/:id' => 'lifts#destroy'

  #########USERS#########

  get '/users' => 'users#index', as: :users_index

  post '/users' => 'users#create'

  # get '/users/:id' => 'users#show'

  get '/users/workouts/:id' => 'users#show_workouts'

  delete '/lifts/:id' => 'lifts#destroy'


  ######WORKOUTS######
  #show all workouts as a link
  get '/workouts' => 'workouts#index', as: :workouts_index

  get '/workouts/new' => 'workouts#new', as: :new_workout


  post '/workouts' => 'workouts#create', as: :workouts_create


  #show details of a specific workout
  get '/workouts/:id' => 'workouts#show'

  #to delete a single video
  #I'll come back to this
  #delete '/workouts/videos/:id' => 'lifts#destroy'

end

#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#        user_registration POST   /users(.:format)               devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy

app/models/lift.rb
class Lift < ActiveRecord::Base
  has_many :videos
  belongs_to :user
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :videos
  has_many :workouts
  has_many :lifts
  attr_accessible :email, :password, :username, :password_confirmation, :name

  def after_create(user)
    user.lifts.create(:name => "Cardio")
    user.lifts.create(:name => "Plyometrics")
    user.lifts.create(:name => "Upperbody")
    user.lifts.create(:name => "Lowerbody")
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :workouts
  belongs_to :lift
  attr_accessible :name, :url, :description, :lift_id
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_and_belongs_to_many :videos
  belongs_to :user
  attr_accessible :name, :description, :video_ids
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

   helper_method :yt_client


  def yt_client
    @yt_client ||= YouTubeIt::Client.new(:username => YouTubeITConfig.username , :password => YouTubeITConfig.password , :dev_key => YouTubeITConfig.dev_key)
  end
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController

  #Show all lift categories
  def index
    @lifts = current_user.lifts
    @lift = Lift.new
    @videos = current_user.videos
    @user = current_user

    # @videos = current_user.videos

  end

  #show all videos in a given category
  def show
    @lift = Lift.find(params[:id])
    @videos = Lift.find(params[:id]).videos
  end

  #show all videos
  def lifts_videos
    @videos = current_user.videos
  end

  #need to create a new lift category
  def create
    @lift = Lift.new(params[:lift])
    current_user.lifts << @lift

    redirect_to lifts_index_path
  end

  #delete a specific video from a lift
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    redirect_to '/lifts', notice: "video deleted"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users

  def index
    if current_user
      redirect_to '/profile'
    end
    @user = current_user
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: "new"
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
  end


  def search
  end

  #show all the videos resulting from a search entered
  #in the search actions
  def videos
    @client = YouTubeIt::Client.new
    @videos = @client.videos_by(:query => params[:description])
    @lifts = Lift.all
    @video = Video.new
  end


  def show
    #for testing
    #will actually be displayed in lifts#index.
    #I may not use this page but will add it
    # in the future when I can embed videos, add
    # favorite tag, and add workout tag.
    @saved_videos = Video.all
  end

  def new
  end

  #save a video to the database and add video to
  #a lift category
  def create
    name = params[:name]
    description = params[:video][:description]
    url = params[:url]
    lift_id = params[:video][:lift_id]
    # video = Video.create(:name => params[:name], :url => params[:url], :description => params[:description], :lift_id => [params[:lift_id]])
    video = Video.new
    video.name = name
    video.description = description
    video.url = url
    video.lift_id = lift_id
    current_user.videos << video

    redirect_to '/lifts'
    #redirect_to '/lifts/#{video.lift_id}'
    end
  end

  #delete video
  # def destroy
  #   video = Video.find(params[:id])
  #   video.destroy
  #   redirect_to('/contacts')
  # end
# end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  #show workout links/ create workout
  def index
    @workouts = current_user.workouts
  end

  #action for creating a new workout name, desc, and adding videos
  def new
    @user = current_user
    @workout = Workout.new
  end

  #create new workout
  def create
    @workout = Workout.create(params[:workout])
    current_user.workouts << @workout

    redirect_to '/workouts'
  end

  def show
    workout_id = params[:id]
    @workout = Workout.find_by_id(workout_id)
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutBuilder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>
<body>
  <nav class="navbar-inner">
    <li><%= link_to "Home", index_path %></li>
    <li><%= link_to "Search", search_path %></li>
    <li><%= link_to "My Lifts", lifts_index_path %></li>
    <li><%= link_to "My Workouts", workouts_index_path %></li>
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
  </nav>


<main role="main">
    <div class="container">
    <div class="content alinacenter">
      <div class="row">
        <div class="span12">

          <% if notice %>
              <p class="notice"><%= notice %></p>
          <% end %>
          <% if alert %>
              <p class="alert"><%= alert %></p>
          <% end %>
          <br />
          <%= yield %>
        </div>
      </div>
      <footer>
      </footer>
    </div>
  </div>
</main>

</body>
</html>

app/views/lifts/index.html.erb
<h1>Lifts</h1>

<% if @user.lifts.count != 0 %>
  <div id="liftsIndex">
    <ul>
      <% @lifts.each do |lift| %>
        <li><h3><a href="/lifts/<%= lift.id %>"><%= lift.name %></a></h3>
         (<%= lift.videos.count %>)
        </li></br>
      <% end %>
        <li><h3><%= link_to "All Videos",  lifts_videos_path %></h3> (<%= @videos.count %>)
        </li>
    </ul>
  </div>

  <div id="newLiftForm">
    <h3>Create new lift category</h3>
    <h6>This will be added to the dropdown in video search</h6>
    <%= form_for(@lift, :url => videos_path, :method => :post) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, :placeholder => "Chest, cardio, shoulders, etc." %>
      <%= f.submit %>
    <% end %>
  </div>

<% else %>

  <div id="newLiftForm">
    <h3>Create new lift category</h3>
    <h6>This will be added to the dropdown in video search</h6>
    <%= form_for(@lift, :url => videos_path, :method => :post) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, :placeholder => "Chest, cardio, shoulders, etc." %>
      <%= f.submit %>
    <% end %>
  </div>

<% end %>

app/views/lifts/lifts_videos.html.erb
<h1>Your workout videos!</h1>

  <ul style="text-align:center; background-color:#F6F6F6">
  <% @videos.each do |video| %>
    <li><%= link_to video.name, video.url, :target => '_blank' %>
        (<%= video.lift_id %>)
  <%= button_to "delete", {:controller => :lifts,
        :action => 'destroy', :id => video.id },     :method => :delete %>
    </li>
    <% end %>
  </ul>

app/views/lifts/show.html.erb
<h1><%= @lift.name %></h1>

<ul style="text-align:center; background-color:#F6F6F6">
  <% @videos.each do |video| %>
  <li><a href="<%= video.url %>" target="_blank"><%= video.name %></a>
      <ul>
        <li><%= video.description %></li>
        <li>Date Added: <%= video.created_at %></li>
      </ul>
<%= button_to "delete", {:controller => :lifts,
      :action => 'destroy', :id => video.id },     :method => :delete %>
  </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>Welcome to WorkoutBuilder</h1>
<p class="lead">WorkoutBuilder is the best way to find and quickly reference exercise specific instructional videos on YouTube. It allows you to find and reference videos based on muscle category or a specific workout that you create!.</p>

<div style="margin-left:150px">
<img src="http://irrationalfitness.com/wp-content/uploads/2012/04/weights1.jpg">
</div>

<div class="iconClass">
<div class="span4" id="a"></div>
<div class="span4" id="b"></div>
<div class="span4" id="c"></div>
</div>

app/views/users/profile.html.erb
<div class="profile_index_class">
  <h1>Welcome to WorkoutBuilder, <%= current_user.username %>!</h1>

  <br />
  <ul class="home">
    <%= link_to "Home", index_path %>
  <%= link_to "Search", search_path %>
  <%= link_to "My Lifts", lifts_index_path %>
  <%= link_to "My Workouts", workouts_index_path %></ul>
  </br>
  </br>
  <div class="lead">WorkoutBuilder is the best way to find and quickly reference exercise specific instructional videos on YouTube. It allows you to find and reference videos based on muscle category or a specific workout that you create!</div>


  <div class="iconClass">
    <div class="span4" id="a">
      <h5>Create a lift category</h5>
    </div>
    <div class="span4" id="b">
      <h5>Search and save videos from YouTube</h5>
    </div>
    <div class="span4" id="c">
      <h5>Create and save videos to a workout</h5>
    </div>
  </div>
  </div>

app/views/videos/search.html.erb
<h1>Search for a Video!</h1>

<div id="search">
<%= form_tag("/search/videos", method: "get") do %>
  <%= label_tag(:description, "Search:") %>
  <%= text_field_tag(:description) %>
  <%= submit_tag("Search") %>
<% end %>
</div>

 <div class="span4" id="b" style="text-align:center; margin-left:300px; margin-right:auto">
      <h5>Search and save videos from YouTube</h5>
    </div>

app/views/videos/videos.html.erb
<div id="videoSearch">
  <% @videos.videos.each do |video| %>
  <div style="text-align:left; margin-left:200px; background-color: #F6F6F6">
  <ul>
    <li><%= link_to video.title, video.player_url,
     :target => '_blank' %>
      <% if video.rating.nil? %>
      <ul>
        <li>Views: <%= video.view_count %></li>
        <li><%= "no rating" %></li>
      </ul>
      <% else %>
      <ul>
        <li>Views: <%= video.view_count %></li>
        <li>Average rating: <%= video.rating.average %></li>
        <li>Likes: <%= video.rating.likes %></li>
        <li>Dislikes: <%= video.rating.dislikes %></li>
        <li>Total votes: <%= video.rating.rater_count %></li>
    </ul>
  </div>
    <% end %>
  </br>


<%= form_for(@video, :url => create_path, :method => :post)  do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= hidden_field_tag :url, video.player_url  %>
  <%= hidden_field_tag :name, video.title %>
  <%= collection_select :video, :lift_id, Lift.all, :id, :name%>

  <%= f.submit %>
</ul>
<% end %>

<% end %>
</div>

app/views/workouts/index.html.erb
<h1>Workouts</h1>

<div id="workoutsIndex">
<ul>
  <% @workouts.each do |wo| %>
    <li><h4><a href="/workouts/<%= wo.id %>"><%= wo.name %></a></h4> (<%= wo.videos.count %> videos)
      <% if wo.description.nil? %>
        <%= %>
      <% else %>
      <ul>
        <li><%= wo.description %></li>
      </ul>
      <% end %>
    </li></br>
  <% end %>
</ul>
</div>


<h3 style="text-align:center; padding-top:25px"><%= link_to "Create Workout", new_workout_path %></h3>

app/views/workouts/new.html.erb
<h1>Create a workout now!</h1>

  <%= form_for(@workout, :url => workouts_create_path, :method => :post) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :placeholder => "Chest day, cardio day, etc." %>
  <%= f.label :description %>
  <%= f.text_field :description, :placeholder => "This workout is mostly sprints" %>

<h4>Select videos for this workout</h4>
  <% @user.videos.each do |video| %>
    <%= link_to video.name, video.url, :target => '_blank' %> <%= Lift.find(video.lift_id).name %></br>
    <%= check_box_tag "workout[video_ids][]", video.id, @workout.videos.include?(video) %></br>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/workouts/show.html.erb
<h1>This is workout <%= @workout.name %><h6 style="text-align:center">(Created: <%= @workout.created_at %>)<h6></h1>


<ul style="text-align:center; background-color:#F6F6F6">
<% @workout.videos.each do |video| %>
  <li><%= link_to video.name, video.url, :target => '_blank' %> ( <%= Lift.find(video.lift_id).name %> ) </li>
  <% end %>
</ul>